// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH4SODO1TsKaCClVo4EctZfcwdI3ai7g0',
    appId: '1:771210896090:web:e750b29dab1ad2d541fbe3',
    messagingSenderId: '771210896090',
    projectId: 'firstfirebase-1e79e',
    authDomain: 'firstfirebase-1e79e.firebaseapp.com',
    databaseURL: 'https://firstfirebase-1e79e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'firstfirebase-1e79e.appspot.com',
    measurementId: 'G-29LXXHBMCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3aoV3jEuOUw3T8QrrlyoqkM4PNuQzT_k',
    appId: '1:771210896090:android:16afdb9e64596e2e41fbe3',
    messagingSenderId: '771210896090',
    projectId: 'firstfirebase-1e79e',
    databaseURL: 'https://firstfirebase-1e79e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'firstfirebase-1e79e.appspot.com',
  );
}
